resilience4j.circuitbreaker.instances.meuCircuitBreaker.minimumNumberOfCalls=2
resilience4j.circuitbreaker.instances.meuCircuitBreaker.slidingWindowSize=2
resilience4j.circuitbreaker.instances.meuCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.meuCircuitBreaker.waitDurationInOpenState=5s
resilience4j.circuitbreaker.instances.meuCircuitBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.meuCircuitBreaker.slidingWindowType=COUNT_BASED